/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    Option: typeof import('./src/components/Option.vue')['default']
    Sheet: typeof import('./src/components/sheet.vue')['default']
    TopButton: typeof import('./src/components/TopButton.vue')['default']
  }
}
